---
name: pre-commit

on:  # yamllint disable rule:truthy
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    if: github.repository == 'WIJIT-tech/pyk8sdev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: |
            .pre-commit-config.yaml
            pyproject.toml
      - run: uv sync --group pre-commit
      - uses: tox-dev/action-pre-commit-uv@v1
