---
name: publish

on:  # yamllint disable rule:truthy
  # zizmor: ignore[concurrency-limits] only runs on tags, tags are set to be immutable
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

permissions: {}

jobs:
  publish:
    name: Publish to PyPI
    if: github.repository == 'WIJIT-tech/pyk8sdev'
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write  # Required for Trusted Publishing to identify itself to PyPI (https://docs.pypi.org/trusted-publishers/using-a-publisher/)
      contents: read  # Required to check the repo out (https://github.com/actions/checkout?tab=readme-ov-file#recommended-permissions)
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
        with:
          enable-cache: false
      - name: Build
        run: uv build
      - name: Attest
        run: uv tool run pypi-attestations sign dist/*
      - name: Publish
        run: uv publish
